# Generated by Django 4.2.3 on 2023-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
